name: Build Academicons Fonts

on: [push, pull_request]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Get sources
        uses: actions/checkout@v1

      - name: Install dependencies
        run: |
          sudo apt-get install zlib1g-dev fontforge jq yui-compressor

          for repo in bramstein/sfnt2woff-zopfli google/woff2 wget/sfnt2woff; do
            dir=${TMPDIR:-/tmp}/${repo#*/}
            git clone --recursive https://github.com/$repo $dir
            pushd $dir
            make
            sudo make install || find * -maxdepth 0 -type f -executable -exec sudo cp -v {} /usr/local/bin/ \;
            popd
          done
          sudo gem install fontcustom

      - name: Keep only specified input files
        run: |
          jq -r 'keys[] | "svg/\(.).svg"' config/codepoints.json > files
          rm -f `find svg/ -type f | grep -vFxf files`
          ls `cat files` > /dev/null

      - name: Build fonts
        run: |
          # Pre-populate manifest with fixed codepoints, by populating the glyphs from config/manifest-template.json
          # with the contents of config/codepoints.json
          jq '.glyphs = ($points[0] | with_entries({key: .key, value: {codepoint: .value}}))' \
            --slurpfile points config/codepoints.json config/manifest-template.json > .fontcustom-manifest.json
          fontcustom compile

      - name: Add minified css
        run: |
          yui-compressor -o academicons/css/academicons.min.css academicons/css/academicons.css

      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: academicons
          path: |
            academicons


  test:
    name: Test
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Get sources
        uses: actions/checkout@v1

      - name: Download the built sources
        uses: actions/download-artifact@v2
        with:
          name: academicons
          path: .

      - name: Install dependencies
        run: |
          sudo apt-get install python3-selenium imagemagick

      - name: Diff glyph table
        run: |
          ./test/capture.py -d firefox test/glyph-table.new.png
          npxdiff=`compare -metric AE -fuzz 25% test/glyph-table.png test/glyph-table.new.png test/glyph-table.diff.png || :`
          echo $npxdiff pixels differ

      - name: Upload table diff
        uses: actions/upload-artifact@v2
        with:
          name: diff-glyphs
          path: |
            test/glyph-table.diff.png
