name: Build Academicons Fonts

on: [push, pull_request]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Get sources
        uses: actions/checkout@v1

      - name: Install dependencies
        run: |
          sudo apt-get install zlib1g-dev fontforge jq yui-compressor

          for repo in bramstein/sfnt2woff-zopfli google/woff2 wget/sfnt2woff; do
            dir=${TMPDIR:-/tmp}/${repo#*/}
            git clone --recursive https://github.com/$repo $dir
            pushd $dir
            make
            sudo make install || find * -maxdepth 0 -type f -executable -exec sudo cp -v {} /usr/local/bin/ \;
            popd
          done
          sudo gem install fontcustom

      - name: Build fonts
        run: |
          # Pre-populate manifest with fixed codepoints, by populating the glyphs from config/manifest-template.json
          # with the contents of config/codepoints.json
          jq '.glyphs = ($points[0] | with_entries({key: .key, value: {codepoint: .value}}))' \
            --slurpfile points config/codepoints.json config/manifest-template.json > .fontcustom-manifest.json
          fontcustom compile

      - name: Add minified css
        run: |
          yui-compressor -o academicons/css/academicons.min.css academicons/css/academicons.css

      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: academicons
          path: |
            academicons


  test:
    name: Test
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Get sources
        uses: actions/checkout@v1

      - name: Install dependencies
        run: |
          sudo apt-get install python3-selenium imagemagick
          mv test/glyph-table.png test/glyph-table.curent.png

      - name: Download the built sources
        uses: actions/download-artifact@v2
        with:
          name: academicons
          path: .

      - name: Diff glyph table
        run: |
          ./test/capture.py -d firefox test/glyph-table.png
          npxdiff=`compare -metric AE -fuzz 25% test/glyph-table.curent.png test/glyph-table.png test/glyph-table.diff.png || :`
          echo "::set-output name=PXDIFF::$npxdiff"
          id: image-diff


      - name: Upload table diff to gist
        uses: actions/upload-artifact@v2
        with:
          name: diff-glyphs
          path: |
            git clone $GIST_URL image-gist && cd image-gist

            cp ../test/glyph-table.diff.png ../test/glyph-table.png ./
            git add glyph-table.diff.png glyph-table.png
            git commit -am "Images generated from $GITHUB_SHA"

            gistsha=$(git rev-parse HEAD)
            git push https://${TOKEN}@${GIST_URL#https://}

            cd ..

            image_url=${GIST_URL/github./githubusercontent.}/raw/$gitsha/glyph-table.diff.png
            echo "::set-output name=URL::$image_url"
            id: image-upload
          env:
            GIST_URL: https://gist.github.com/lucjaulmes/1df00b3e5e24e32f4eb56de5dbc934f3
            TOKEN: ${{ secrets.GIST_PUSHER }}

      - name: Sum up diff ?
        run: |
          echo "Commit caused ${{ steps.image-diff.outputs.PXDIFF }} pixels difference, diff at ${{ steps.image-upload.outputs.URL }}"

